// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk864dRCOHxS9vRW1YlGvX_GhS-fy_tCk',
    appId: '1:434359681274:web:62d50c3a7c781f1ff0c943',
    messagingSenderId: '434359681274',
    projectId: 'todo-app-85cb3',
    authDomain: 'todo-app-85cb3.firebaseapp.com',
    storageBucket: 'todo-app-85cb3.appspot.com',
    measurementId: 'G-NGZNH3NWQF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7DFnkbfkFg0Rd5t1Tqi9eUIPQb8MOUqA',
    appId: '1:434359681274:android:78a03224968c969df0c943',
    messagingSenderId: '434359681274',
    projectId: 'todo-app-85cb3',
    storageBucket: 'todo-app-85cb3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtrc9KNz6A96ZXZEJ46cIO_EWyUW24eeA',
    appId: '1:434359681274:ios:03807ec6deaa3372f0c943',
    messagingSenderId: '434359681274',
    projectId: 'todo-app-85cb3',
    storageBucket: 'todo-app-85cb3.appspot.com',
    iosBundleId: 'com.example.newApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtrc9KNz6A96ZXZEJ46cIO_EWyUW24eeA',
    appId: '1:434359681274:ios:03807ec6deaa3372f0c943',
    messagingSenderId: '434359681274',
    projectId: 'todo-app-85cb3',
    storageBucket: 'todo-app-85cb3.appspot.com',
    iosBundleId: 'com.example.newApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBk864dRCOHxS9vRW1YlGvX_GhS-fy_tCk',
    appId: '1:434359681274:web:5ef67a85bd4a2d3af0c943',
    messagingSenderId: '434359681274',
    projectId: 'todo-app-85cb3',
    authDomain: 'todo-app-85cb3.firebaseapp.com',
    storageBucket: 'todo-app-85cb3.appspot.com',
    measurementId: 'G-G9ZJD1LC4W',
  );

}